id: P010478
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG13166
  title: བོད་ཀྱི་གཅེས་ཕྲུག
  author: ''
  volumes:
    0f2e62afc53b4b969a730491dea0030b:
      image_group_id: I1KG13483
      title: ''
      volume_number: 1
      total_pages: 384
      base_file: v001.txt
