id: I33477AF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:52:24+00:00'
last_modified: '2022-06-08T13:53:58.336057+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13166
  title: བོད་ཀྱི་གཅེས་ཕྲུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    E069:
      image_group_id: I1KG13483
      title: ''
      total_pages: 384
      order: 1
      base_file: E069.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
